#:schema node_modules/wrangler/config-schema.json
name = "spider-iptv"
pages_build_output_dir = "./dist" # 构建后的静态文件目录（如 Vite 为 ./dist, Next.js 为 ./out）
compatibility_date = "2026-02-23" # 使用当前的兼容性日期

[vars]
# 生产环境全局变量
API_URL = "https://tv.clun.top"
#NODE_VERSION = "24.0.0"

#[build]
#command = "npm run build" # 构建指令
#watch_dir = "./src"        # 本地开发监听目录

# 绑定 KV 命名空间
#[[kv_namespaces]]
#binding = "MY_KV"
#id = "xxxxxxxxxxxxxx"

# 绑定 D1 数据库
#[[d1_databases]]
#binding = "DB"
#database_name = "prod-db"
#database_id = "xxxxxxxxxxxxxx"

# 绑定 R2 存储桶
#[[r2_buckets]]
#binding = "BUCKET"
#bucket_name = "my-assets"

# 预览环境配置（用于部署预览分支）
[env.preview.vars]
API_URL = "https://tv.clun.top"

#[env.preview]
#[[d1_databases]]
#binding = "DB"
#database_name = "preview-db"
#database_id = "yyyyyyyyyyyyyy"
